---
- name: Install nginx package
  apt: name=nginx state=present

# - name: Create nginx configuration file
#   copy: src=default.conf dest=/etc/nginx/sites-available/default.conf
#   notify:
#     - reload nginx

- name: Ensure nginx is running
  service: name=nginx state=started enabled=yes
