---
- name: Install Mongodb package
  apt: name={{ item }} state=present
  with_items:
    - mongodb

- name: run mongodb
  service:
    name: mongodb
    state: started
    enabled: yes
    daemon_reload: yes
