---
- name: Install uwsgi package
  pip:
    name: uwsgi

- name: Create socket directory
  file:
  path: /etc/uwsgi/pools.d/
    state: directory

- name: Copy socket configs
  copy: src=pools/ dest=/etc/uwsgi/pools.d/
  notify:
    - Restart nginx

- name: Copy uwsgi params for nginx
  copy:
    src: uwsgi_params
    dest: /etc/nginx/uwsgi_params
  notify:
    - Restart nginx

- name: Check nginx configuration syntax
  command: /usr/sbin/nginx -t
