---
- name: Set-up adams, the secondary VM
  hosts: adams
  user: root


  roles:
    - common
    - sshkeys
    - role: kerberos_server
      tags:
        - kerberos_server

    - role: oauth
      tags: oauth

