---
- name: Set-up adams, the secondary VM
  hosts: adams
  user: root


  roles:
    - common
    - sshkeys
    - role: kerberos_server
      tags:
        - kerberos_server

#    - role: oauth
#      tags: oauth

    - role: postfix
      postfix_mailname: adams.ugent.be
      postfix_hostname: adams.ugent.be
      postfix_alias_maps:
        - "hash:/etc/aliases"
        - "ldap:/etc/postfix/ldap-users.cf"
      postfix_destinations:
        - zeus.ugent.be
        - localhost
        - adams.ugent.be
        - king.ugent.be
        - kelder.zeus.ugent.be
      postfix_fallback: #Geen
      tags: postfix

