---
- name: Configure Asimov
  hosts: asimov
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name:
          - vim
          - htop
          - nmap
          - unzip
          - tmux

  roles:
    - role: sshkeys
      tags: sshkeys
