---
- name: Configure Asimov
  hosts: asimov
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name:
          - vim
          - htop
          - nmap
          - unzip
          - tmux

  roles:
    - role: sshkeys
      tags: sshkeys

    - role: ssh-config
      tags: ssh-config

    - role: nginx_base
      tags: nginx

    - role: nginx_vhost
      nginx_vhost_file: 'join.12urenloop.be'
      tags:
        - join
        - nginx