---
- name: Raise dick.
  hosts: dick
  user: root


  roles:
    - common
    - sshkeys
    - router
    - role: sshtunnel
      sshtunnel_remote_host: adams
      sshtunnel_remote_url: adams.ugent.be
      tags: sshtunnel

  vars_files:
    - vars/firewall_rules.yml
