---
- name: Raise dick.
  hosts: dick
  user: root


  roles:
    - common
    - sshkeys
    - router
    - role: sshtunnel
      sshtunnel_remote_host: adams
      sshtunnel_remote_url: adams.ugent.be
      sshtunnel_forwards:
        - local_port: 88
          remote_port: 88
        - local_port: 543
          remote_port: 543
        - local_port: 544
          remote_port: 544
        - local_port: 749
          remote_port: 749
        - local_port: 754
          remote_port: 754

      tags: sshtunnel
    - role: kerberos_client
      kerberos_client_kdc: 127.0.0.1
      kerberos_client_kadmin: 127.0.0.1
      tags: kerberos_client

  vars_files:
    - vars/firewall_rules.yml
