---
- name: Set-up Herbert, the best VM
  hosts: herbert
  user: root

  tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install utilities
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - ack-grep
        - vim
        - zsh
        - tmux
        - htop
        - tree
        - curl
        - unrar
        - unzip
        - etckeeper
        - git-core
        - nodejs
        - yarn
        - cifs-utils  # share stuff
        - speedtest-cli
        - nmap
        - sudo

  roles:
    - role: sshkeys
      tags: sshkeys

    ###############################
    # chat.zeus.gent (Rocketchat) #
    ###############################

    # NodeJS global
    # (rocketchat will install a local version, but the global version is 
    # needed to install  the N version manager)
    - role: nodejs
      nodejs_version: 10.x
      tags:
        - rocketchat

    # Database: MongoDB
    # TODO: currently a custom mongoDB version is provided by
    #       the rocketchat role, but we want our own role for that
    # - role: mongodb
    #  tags:
    #    - mongodb
    #    - rocketchat

    # vhost file for our reverse proxy
    - role: nginx_vhost
      nginx_vhost_file: 'chat.zeus.gent'
      tags:
        - nginx
        - rocketchat

    # The actual Rocket.Chat role (https://github.com/RocketChat/Rocket.Chat.Ansible)
    # Currently a fork which supports debian 9: 
    # https://github.com/RocketChat/Rocket.Chat.Ansible/pull/89
    # TODO: use the normal role when PR is merged
    - role: Rocket.Chat.Ansible
      rocket_chat_service_host: chat.zeus.gent
      # automatic upgrades does not mean that rocket.chat will update itself,
      # when ansible runs and the version changes, the ansible role will
      # migrate to the newest version
      # ! Only set this to true when an upgrade has to be done, otherwise
      # it will always perform the (slow) steps to upgrade
      rocket_chat_automatic_upgrades: false
      rocket_chat_include_nginx: false
      tags:
        - rocketchat
