---
- name: Set-up Herbert, the best VM
  hosts: herbert
  user: root


  roles:
    #    - common
    #    - nginx_sites_herbert
    #    - mongodb
    - role: Rocket.Chat.Ansible
      rocket_chat_automatic_upgrades: true
      rocket_chat_include_nginx: false
      rocket_chat_include_mongodb: false

