---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root


  roles:
#    - common
#    - franklinkim.sudo
    - users
#    - logrotate
#    - kerberos
#    - mariadb
#    - iptables
#    - nginx
#    - php
#    - python
#    - shares
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - postfix
#    - mailman
#    - new_relic
#    - fail2ban
#    - phpmyadmin
#    - ntp
#    # Ruby, rails, passenger stuff
#    - zzet.rbenv
#    - bundler # enable this when installing a new rbenv version using zzet.rbenv
#    - common-rails
#    - passenger
#    # Python stuff
#    - common-python
#    # Nodejs
#    - common-nodejs
#    # User configs and stuff
#    - mysql_configs
#    - nginx_configs
#    - django
#    - user_configs
#    - uwsgi
    - dokuwiki
#    # Letsencrypt thingies
#     - ansible-letsencrypt # Walktrough: https://github.com/ZeusWPI/ansible-config/wiki/Steps-for-LetsEncrypt
#    # Matrix
#    - matrix
#    # Monitoring goodies
#    - ansible-playbook-monit
#    - sshkeys

  vars_files:
    - vars/passwords.yml
    - vars/ruby.yml
    - vars/matrix.yml
    - vars/monit.yml
    - vars/letsencrypt.yml
