---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root


  roles:
     - sshkeys
#    - common
#    - bottlebats
#    - franklinkim.sudo
#    - users
#    - logrotate
#    - {role: kerberos_client, kerberos_client_kdc: zeusgw.ugent.be, kerberos_client_kadmin: zeusgw.ugent.be }
#    - mariadb
#    - iptables
#    - nginx_base
#    - php
#    - python
#    - shares
#    # Email stuff
#    - spamassassin
#    - mail_antivirus
#    - postfix
#    - mailman
#    - new_relic
#    - fail2ban
#    - phpmyadmin
#    - ntp
#    # Ruby, rails, passenger stuff
#    - zzet.rbenv
#    - bundler # enable this when installing a new rbenv version using zzet.rbenv
#    - common-rails
#    - passenger
#    # Python stuff
#    - common-python
#    # Nodejs
#    - common-nodejs
#    # User configs and stuff
#    - mysql_configs
#    - nginx_sites_king
#    - django
#    - user_configs
#    - uwsgi
#    - dokuwiki
#    # Letsencrypt thingies
#    - ansible-letsencrypt # Walktrough: https://github.com/ZeusWPI/ansible-config/wiki/Steps-for-LetsEncrypt
#    # Matrix
#    - matrix
#    # Monitoring goodies
#    - ansible-playbook-monit
#    - matrix

  vars_files:
    - vars/passwords.yml
    - vars/ruby.yml
    - vars/monit.yml
    - vars/letsencrypt_king.yml
