---
- name: Set-up the entire zeus-infrastructure
  hosts: all
  user: root
  sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - ruby

- name: Set up NAS
  hosts: abyss
  user: root
  sudo: yes

  roles:
    - rsnapshot
