---
- name: Set-up the entire Zeus infrastructure
  hosts: king
  user: root

  roles:
    - common
    - mysql
    - nginx
    - php
    - passenger
    - ruby_and_rails
    - python
    - nginx_configs  # Install nginx configs after fcgi and passenger are installed
