---
- name: Set-up svfs, Subnet Visualisation For Sysadmin
  hosts: svfs
  user: root

  vars_files:
    - vars/authorized_keys.yml

  pre_tasks:
    - name: Update system
      apt:
        update_cache: yes
      tags: update

    - name: Install Packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - gcc
        - vim
        - make
        - curl
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
        - nano

  roles:
    - role: sshkeys
      extra_keys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwkFVCicEFEjZiNfqpuuFhBTrAxuAo538i++hPv0v/laUVJUEIS1EFnkoYRZ97ygqLqWobn8hvXcM+dUf1VqTOK+6Yb9+MvPq5uFlKc9+4c7ZvgYZkB52lYGkgUrrl/TxJWTTsyLPau1Iv5ER81kJNIUacUd/N1zq0zqB8+9Tu5j6RSmCENys3u3UqF/Lgp0im72ZYqoI+x+g0A2ugYDgkI8kTY/8p6ashXTyUpSUDRWaMdIfXC420evwa2vscFS3O9oSWTlrcO/7E8Ymd/GF7eOt0iCENvSWmk/36geNxjTrzYZcZhPXp38VfezHnZT1m1Lm1eqJ0LGXcEq/T3iMYH/PekVT1vsO1uSsCfYElDgvAzDzG0PCtBfyp9Ke8jD3yhPgUxmUkOY2/HQ7kWX+BEqShUGUCZG5g+QDzoATfzUa5sGn6WBJjRsNhM332gv1ESK6d9lTChYKliaL9LW/EBAJzd/hoiWgwUY5sKoPQk15H62ditObIZtM+XtL4GbM= fklinck@fkmachine'
      tags: sshkeys

    - role: fail2ban
      tags: fail2ban

    - role: nginx_vhost
      nginx_vhost_file: 'svfs.kelder.zeus.ugent.be'
      tags:
        - nginx

    - role: user
      user_name: svfs
      user_authorized_keys: "{{ authorized_keys }}\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwkFVCicEFEjZiNfqpuuFhBTrAxuAo538i++hPv0v/laUVJUEIS1EFnkoYRZ97ygqLqWobn8hvXcM+dUf1VqTOK+6Yb9+MvPq5uFlKc9+4c7ZvgYZkB52lYGkgUrrl/TxJWTTsyLPau1Iv5ER81kJNIUacUd/N1zq0zqB8+9Tu5j6RSmCENys3u3UqF/Lgp0im72ZYqoI+x+g0A2ugYDgkI8kTY/8p6ashXTyUpSUDRWaMdIfXC420evwa2vscFS3O9oSWTlrcO/7E8Ymd/GF7eOt0iCENvSWmk/36geNxjTrzYZcZhPXp38VfezHnZT1m1Lm1eqJ0LGXcEq/T3iMYH/PekVT1vsO1uSsCfYElDgvAzDzG0PCtBfyp9Ke8jD3yhPgUxmUkOY2/HQ7kWX+BEqShUGUCZG5g+QDzoATfzUa5sGn6WBJjRsNhM332gv1ESK6d9lTChYKliaL9LW/EBAJzd/hoiWgwUY5sKoPQk15H62ditObIZtM+XtL4GbM= fklinck@fkmachine"
      tags:
        - user
