---
- name: Create user
  user:
    name: oauth
    home: /srv/oauth
    createhome: yes
    system: yes

- name: Clone Git repo
  git:
    repo: git@github.com:ZeusWPI/oauth.git
    dest: /srv/oauth/
    accept_hostkey: yes
  notify: Restart oauth

- name: Copy (and fill in secrets) local_settings.py
  template:
    src: local_settings.py
    dest: /srv/oauth/oauth/local_settings.py

- name: Fix permissions
  file:
    path: /srv/oauth/
    owner: oauth
    group: oauth
    recurse: yes
    mode: "u=rwx,g=rx,o="

- name: Manage pip & virtualenv
  pip:
    chdir: /srv/oauth/
    requirements: /srv/oauth/requirements.txt
    virtualenv: /srv/oauth/.venv
  notify: Restart oauth

- name: Run collactstatic command
  command: '/srv/oauth/.venv/bin/python2.7 manage.py collectstatic'
  args:
    chdir: /srv/oauth/
  become_user: oauth
  become: yes

- name: Copy systemd unit
  template:
    src: systemd/oauth.service
    dest: /etc/systemd/system/
  register: oauth_unit

- name: Reload systemd-daemon when needed
  command: systemctl daemon-reload
  when: oauth_unit.changed

- name: Check if database is present
  find:
    path: /srv/oauth/db.sqlite3
  register: oauth_db

- name: Allow to place a database if there isn't one present
  pause:
    prompt: 'No database file found. If you want, you can copy a backup to /srv/oauth/db.sqlite3. Hit enter when you are ready.'

- name: Start & enable service
  service:
    name: oauth
    state: started
    enabled: yes

