---
- name: Install librkb5-dev
  apt:
    pkg: libkrb5-dev
    state: latest
    update_cache: yes
  tags: install

- name: Create user
  user:
    name: oauth
    home: /srv/oauth
    createhome: yes
    system: yes

- name: Clone Git repo
  git:
    repo: git@github.com:ZeusWPI/oauth.git
    dest: /srv/oauth/app/
    accept_hostkey: yes
    force: yes
  notify: Restart oauth

- name: Fix permissions
  file:
    path: /srv/oauth/app/
    owner: oauth
    group: www-data
    recurse: yes
    mode: "u=rwx,g=rx,o="

- name: Create log directory
  file:
    path: /var/log/oauth
    state: directory
    owner: oauth
    group: www-data

- name: Copy (and fill in secrets) local_settings.py
  template:
    src: local_settings.py
    owner: oauth
    group: oauth
    mode: "u=rwx,g=,o="
    dest: /srv/oauth/app/oauth/local_settings.py


- name: Manage pip & virtualenv
  pip:
    chdir: /srv/oauth/app/
    requirements: /srv/oauth/app/requirements.txt
    virtualenv: /srv/oauth/app/env/
  become_user: oauth
  become: yes
  notify: Restart oauth

- name: Install uWSGI
  pip:
    name: uwsgi
    chdir: /srv/oauth/app/
    virtualenv: /srv/oauth/app/env/
  become_user: oauth
  become: yes
  notify: Restart oauth

- name: Run collectstatic command
  command: '/srv/oauth/app/env/bin/python2.7 manage.py collectstatic --noinput'
  args:
    chdir: /srv/oauth/app/
  become_user: oauth
  become: yes

- name: Copy systemd unit
  copy:
    src: systemd/oauth.service
    dest: /etc/systemd/system/
  register: oauth_unit

- name: Reload systemd-daemon when needed
  command: systemctl daemon-reload
  when: oauth_unit.changed

- name: Check if database is present
  stat:
    path: /srv/oauth/app/db.sqlite3
  register: oauth_db

- debug:
    var: oauth_db

- name: Allow to place a database if there isn't one present
  pause:
    prompt: 'No database file found. If you want, you can copy a backup to /srv/oauth/app/db.sqlite3. Hit enter when you are ready.'
  when: not oauth_db.stat.exists

- name: Start & enable service
  service:
    name: oauth
    state: started
    enabled: yes

