---
- fail:
    msg: "This role currently only supports Debian"
  when: not ansible_distribution == "Debian"

- name: Install FastCGI package for nginx
  apt: name=fcgiwrap state=present
  register: fastcgi_install

- name: Copy FastCGI config file
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/{{ item }}"
  with_items:
    - fastcgi_params
    - fcgiwrap.conf
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Check the configuration file syntax
  command: /usr/sbin/nginx -t

