---
- name: Add matrix repository
  apt_repository:
    repo: 'deb https://matrix.org/packages/debian/ jessie main'
    state: present

- name: Add matrix repository key
  apt_key:
    url: 'https://matrix.org/packages/debian/repo-key.asc'
    state: present

- name: Install matrix and python-cryptography
  apt:
    package: "{{ item  }}"
    state: latest
    update_cache: true
  with_items:
    - matrix-synapse
    - python-cryptography
  tags:
    - install

- name: Add matrix user to letsencrypt group
  user:
    name: matrix-synapse
    groups: letsencrypt
    append: true

- name: Copy matrix homeserver.yaml
  template:
    src: homeserver.yaml
    dest: /etc/matrix-synapse/homeserver.yaml
  notify:
    - Restart matrix

- name: Enable and start matrix
  service:
    name: matrix-synapse
    state: started
    enabled: true
