---
sshtunnel_remote_host: # hostname of the remote server (must be in the hostfile)
sshtunnel_remote_home: "/var/lib/sshtunnel"
sshtunnel_remote_url: # IP or address of the server
sshtunnel_remote_user: sshtunnel # remote user as whom to login on the server
sshtunnel_remote_port: 2222 # SSH port of the server

sshtunnel_local_user: sshtunnel # local user which has access to the server
sshtunnel_local_home: "/var/lib/sshtunnel" # homedir of the local user

# Wheter to execute the sshtunnel with elevated privileges
# (which makes it possible to bind local ports below 1024)
sshtunnel_priviliged: true

sshtunnel_forwards: # forwarding rules
  # Kerberos
  - local_port: 88
    remote_port: 88

# Command which will be executed to open the tunnel
sshtunnel_command: "/usr/bin/ssh {{ sshtunnel_remote_host }} -NF {{ sshtunnel_local_home }}/.ssh/config"
