---
- name: Distro specific installation
  include: "{{ ansible_distribution }}.yml"
  tags: install

- name: Install uwsgi & virtualenv package
  pip:
    name: "{{ item }}"
  with_items:
    - uwsgi
    - virtualenv

- name: Copy uwsgi params for nginx
  copy:
    src: uwsgi_params
    dest: /etc/nginx/uwsgi_params
  notify:
    - Restart nginx

- name: Check nginx configuration syntax
  command: /usr/sbin/nginx -t
