---
- name: Copy socket configs
  copy: src=pools/ dest=/etc/php5/fpm/pool.d/
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy website configs
  copy: src=sites-enabled/ dest=/etc/nginx/sites-available/
  notify:
    - Restart nginx

- name: Copy conf.d configs
  copy: src=conf.d/ dest=/etc/nginx/conf.d/
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy snippets
  copy: src=snippets/ dest=/etc/nginx/snippets/
  notify:
    - Restart nginx

- name: Copy FastCGI configs (1)
  copy: src=fastcgi_params dest=/etc/nginx/fastcgi_params
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy FastCGI configs (2)
  copy: src=fcgiwrap.conf dest=/etc/nginx/fcgiwrap.conf
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Copy uWSGI configs
  copy: src=uwsgi_params dest=/etc/nginx/uwsgi_params
  notify:
    - Restart nginx

- name: Link the configs
  file: src=/etc/nginx/sites-available/{{item | basename}} dest=/etc/nginx/sites-enabled/{{ item | basename }} state=link
  with_fileglob:
    - sites-enabled/*conf
  notify:
    - Restart FastCGI
    - Restart nginx

- name: Check the configuration file syntax
  command: /usr/sbin/nginx -t
