---
- name: Copy website configs
  copy: src=sites-enabled/ dest=/etc/nginx/sites-enabled directory_mode=yes

- name: Enable passenger_root and ruby
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Restart nginx
  service: name=nginx state=restarted
