---
- name: Install UFW
  pacman:
    name: ufw
    state: latest

- name: Enable and start the UFW service
  service:
    name: ufw
    state: started
    enabled: yes

- name: UFW enabled and logging
  ufw:
    state: enabled
    policy: deny
    logging: on

# ATTENTION!
#
# As UFW manages its own state, simply removing a rule here will
# keep the port open. You have to explicitly delete the rule by adding
# `delete: yes`

- name: Allow all internal traffic
  ufw:
    rule: allow
    interface: enp2s1
    src: 10.1.1.0/24

- name: Allow SSH traffic
  ufw:
    rule: allow
    port: 2223

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: 80

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: 443

- name: Route SSH traffic to gygax
  ufw:
    rule: allow
    direcion: in
    port: 2222
    to_ip: 10.1.1.2
    route: yes

