---
- include: '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
  when: ansible_distribution == 'Debian'

- include: '{{ ansible_distribution }}.yml'
  when: ansible_distribution != 'Debian'
