---
- name: Adjust /etc/apt/sources.list
  copy: src=apt/sources.list dest=/etc/apt/sources.list

- name: Import MariaDB Keys
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0xcbcb082a1bb943db

- name: Update apt
  apt: update_cache=yes

- name: Install packages that don't need configuration
  apt: name={{ item }} state=latest
  with_items:
    - ack-grep
    - vim
    - zsh
    - tmux
    - htop
    - tree
    - curl
    - unrar
    - unzip
    - etckeeper
    - git-core
    - drush
    - nodejs
    - cmake
    - cifs-utils  # share stuff
    - speedtest-cli
    # BBB
    - openjdk-8-jdk
    - clang
    - haskell-platform
    - lua5.3

- name: Remove packages we don't want
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - apache2
