---
- name: Copy configuration files
  copy:
    src: network/
    dest: /etc/systemd/network/

- name: Disable NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Enable and restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted
    enabled: yes


