- name: Download ruby ({{ ruby_version }})
  get_url: url=ftp://ftp.ruby-lang.org/pub/ruby/2.0/{{ ruby_version }}.tar.gz dest=/tmp/

- name: extract archive
  command: tar xzf /tmp/{{ ruby_version }}.tar.gz
